/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaudiVisaRouteImport } from './routes/saudi-visa'
import { Route as OtherRouteImport } from './routes/other'
import { Route as MyHandoverRouteImport } from './routes/my-handover'
import { Route as MdPanelRouteImport } from './routes/md-panel'
import { Route as KuwaitVisaRouteImport } from './routes/kuwait-visa'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BmetRouteImport } from './routes/bmet'
import { Route as ActionBoardRouteImport } from './routes/action-board'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorLedgerIndexRouteImport } from './routes/vendor-ledger.index'
import { Route as AgencyLedgerIndexRouteImport } from './routes/agency-ledger.index'
import { Route as VendorLedgerNameRouteImport } from './routes/vendor-ledger.$name'
import { Route as AgencyLedgerNameRouteImport } from './routes/agency-ledger.$name'
import { Route as ApiPublicHandoverAcceptRouteImport } from './routes/api/public/handover-accept'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudiVisaRoute = SaudiVisaRouteImport.update({
  id: '/saudi-visa',
  path: '/saudi-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherRoute = OtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHandoverRoute = MyHandoverRouteImport.update({
  id: '/my-handover',
  path: '/my-handover',
  getParentRoute: () => rootRouteImport,
} as any)
const MdPanelRoute = MdPanelRouteImport.update({
  id: '/md-panel',
  path: '/md-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const KuwaitVisaRoute = KuwaitVisaRouteImport.update({
  id: '/kuwait-visa',
  path: '/kuwait-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BmetRoute = BmetRouteImport.update({
  id: '/bmet',
  path: '/bmet',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionBoardRoute = ActionBoardRouteImport.update({
  id: '/action-board',
  path: '/action-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLedgerIndexRoute = VendorLedgerIndexRouteImport.update({
  id: '/vendor-ledger/',
  path: '/vendor-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyLedgerIndexRoute = AgencyLedgerIndexRouteImport.update({
  id: '/agency-ledger/',
  path: '/agency-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLedgerNameRoute = VendorLedgerNameRouteImport.update({
  id: '/vendor-ledger/$name',
  path: '/vendor-ledger/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyLedgerNameRoute = AgencyLedgerNameRouteImport.update({
  id: '/agency-ledger/$name',
  path: '/agency-ledger/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHandoverAcceptRoute = ApiPublicHandoverAcceptRouteImport.update({
  id: '/api/public/handover-accept',
  path: '/api/public/handover-accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/accounts': typeof AccountsRoute
  '/action-board': typeof ActionBoardRoute
  '/bmet': typeof BmetRoute
  '/help': typeof HelpRoute
  '/invoice': typeof InvoiceRoute
  '/kuwait-visa': typeof KuwaitVisaRoute
  '/md-panel': typeof MdPanelRoute
  '/my-handover': typeof MyHandoverRoute
  '/other': typeof OtherRoute
  '/saudi-visa': typeof SaudiVisaRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/agency-ledger/$name': typeof AgencyLedgerNameRoute
  '/vendor-ledger/$name': typeof VendorLedgerNameRoute
  '/agency-ledger/': typeof AgencyLedgerIndexRoute
  '/vendor-ledger/': typeof VendorLedgerIndexRoute
  '/api/public/handover-accept': typeof ApiPublicHandoverAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/accounts': typeof AccountsRoute
  '/action-board': typeof ActionBoardRoute
  '/bmet': typeof BmetRoute
  '/help': typeof HelpRoute
  '/invoice': typeof InvoiceRoute
  '/kuwait-visa': typeof KuwaitVisaRoute
  '/md-panel': typeof MdPanelRoute
  '/my-handover': typeof MyHandoverRoute
  '/other': typeof OtherRoute
  '/saudi-visa': typeof SaudiVisaRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/agency-ledger/$name': typeof AgencyLedgerNameRoute
  '/vendor-ledger/$name': typeof VendorLedgerNameRoute
  '/agency-ledger': typeof AgencyLedgerIndexRoute
  '/vendor-ledger': typeof VendorLedgerIndexRoute
  '/api/public/handover-accept': typeof ApiPublicHandoverAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/accounts': typeof AccountsRoute
  '/action-board': typeof ActionBoardRoute
  '/bmet': typeof BmetRoute
  '/help': typeof HelpRoute
  '/invoice': typeof InvoiceRoute
  '/kuwait-visa': typeof KuwaitVisaRoute
  '/md-panel': typeof MdPanelRoute
  '/my-handover': typeof MyHandoverRoute
  '/other': typeof OtherRoute
  '/saudi-visa': typeof SaudiVisaRoute
  '/settings': typeof SettingsRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/agency-ledger/$name': typeof AgencyLedgerNameRoute
  '/vendor-ledger/$name': typeof VendorLedgerNameRoute
  '/agency-ledger/': typeof AgencyLedgerIndexRoute
  '/vendor-ledger/': typeof VendorLedgerIndexRoute
  '/api/public/handover-accept': typeof ApiPublicHandoverAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/accounts'
    | '/action-board'
    | '/bmet'
    | '/help'
    | '/invoice'
    | '/kuwait-visa'
    | '/md-panel'
    | '/my-handover'
    | '/other'
    | '/saudi-visa'
    | '/settings'
    | '/tickets'
    | '/users'
    | '/agency-ledger/$name'
    | '/vendor-ledger/$name'
    | '/agency-ledger/'
    | '/vendor-ledger/'
    | '/api/public/handover-accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/accounts'
    | '/action-board'
    | '/bmet'
    | '/help'
    | '/invoice'
    | '/kuwait-visa'
    | '/md-panel'
    | '/my-handover'
    | '/other'
    | '/saudi-visa'
    | '/settings'
    | '/tickets'
    | '/users'
    | '/agency-ledger/$name'
    | '/vendor-ledger/$name'
    | '/agency-ledger'
    | '/vendor-ledger'
    | '/api/public/handover-accept'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/accounts'
    | '/action-board'
    | '/bmet'
    | '/help'
    | '/invoice'
    | '/kuwait-visa'
    | '/md-panel'
    | '/my-handover'
    | '/other'
    | '/saudi-visa'
    | '/settings'
    | '/tickets'
    | '/users'
    | '/agency-ledger/$name'
    | '/vendor-ledger/$name'
    | '/agency-ledger/'
    | '/vendor-ledger/'
    | '/api/public/handover-accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AccountsRoute: typeof AccountsRoute
  ActionBoardRoute: typeof ActionBoardRoute
  BmetRoute: typeof BmetRoute
  HelpRoute: typeof HelpRoute
  InvoiceRoute: typeof InvoiceRoute
  KuwaitVisaRoute: typeof KuwaitVisaRoute
  MdPanelRoute: typeof MdPanelRoute
  MyHandoverRoute: typeof MyHandoverRoute
  OtherRoute: typeof OtherRoute
  SaudiVisaRoute: typeof SaudiVisaRoute
  SettingsRoute: typeof SettingsRoute
  TicketsRoute: typeof TicketsRoute
  UsersRoute: typeof UsersRoute
  AgencyLedgerNameRoute: typeof AgencyLedgerNameRoute
  VendorLedgerNameRoute: typeof VendorLedgerNameRoute
  AgencyLedgerIndexRoute: typeof AgencyLedgerIndexRoute
  VendorLedgerIndexRoute: typeof VendorLedgerIndexRoute
  ApiPublicHandoverAcceptRoute: typeof ApiPublicHandoverAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saudi-visa': {
      id: '/saudi-visa'
      path: '/saudi-visa'
      fullPath: '/saudi-visa'
      preLoaderRoute: typeof SaudiVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other': {
      id: '/other'
      path: '/other'
      fullPath: '/other'
      preLoaderRoute: typeof OtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-handover': {
      id: '/my-handover'
      path: '/my-handover'
      fullPath: '/my-handover'
      preLoaderRoute: typeof MyHandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md-panel': {
      id: '/md-panel'
      path: '/md-panel'
      fullPath: '/md-panel'
      preLoaderRoute: typeof MdPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuwait-visa': {
      id: '/kuwait-visa'
      path: '/kuwait-visa'
      fullPath: '/kuwait-visa'
      preLoaderRoute: typeof KuwaitVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmet': {
      id: '/bmet'
      path: '/bmet'
      fullPath: '/bmet'
      preLoaderRoute: typeof BmetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-board': {
      id: '/action-board'
      path: '/action-board'
      fullPath: '/action-board'
      preLoaderRoute: typeof ActionBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-ledger/': {
      id: '/vendor-ledger/'
      path: '/vendor-ledger'
      fullPath: '/vendor-ledger/'
      preLoaderRoute: typeof VendorLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-ledger/': {
      id: '/agency-ledger/'
      path: '/agency-ledger'
      fullPath: '/agency-ledger/'
      preLoaderRoute: typeof AgencyLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-ledger/$name': {
      id: '/vendor-ledger/$name'
      path: '/vendor-ledger/$name'
      fullPath: '/vendor-ledger/$name'
      preLoaderRoute: typeof VendorLedgerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-ledger/$name': {
      id: '/agency-ledger/$name'
      path: '/agency-ledger/$name'
      fullPath: '/agency-ledger/$name'
      preLoaderRoute: typeof AgencyLedgerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/handover-accept': {
      id: '/api/public/handover-accept'
      path: '/api/public/handover-accept'
      fullPath: '/api/public/handover-accept'
      preLoaderRoute: typeof ApiPublicHandoverAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AccountsRoute: AccountsRoute,
  ActionBoardRoute: ActionBoardRoute,
  BmetRoute: BmetRoute,
  HelpRoute: HelpRoute,
  InvoiceRoute: InvoiceRoute,
  KuwaitVisaRoute: KuwaitVisaRoute,
  MdPanelRoute: MdPanelRoute,
  MyHandoverRoute: MyHandoverRoute,
  OtherRoute: OtherRoute,
  SaudiVisaRoute: SaudiVisaRoute,
  SettingsRoute: SettingsRoute,
  TicketsRoute: TicketsRoute,
  UsersRoute: UsersRoute,
  AgencyLedgerNameRoute: AgencyLedgerNameRoute,
  VendorLedgerNameRoute: VendorLedgerNameRoute,
  AgencyLedgerIndexRoute: AgencyLedgerIndexRoute,
  VendorLedgerIndexRoute: VendorLedgerIndexRoute,
  ApiPublicHandoverAcceptRoute: ApiPublicHandoverAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
